[tool.poetry]
name = "context-collector"
version = "0.1.0"
description = "Collect context for llm chat"
authors = ["chen9z"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
